### ISSUE TITLE
PrivacyManifest file missing

### ISSUE THREAD

**Issue by code-surf** [comapi/comapi-sdk-ios-objc#19]
Apple requires 3rd party libraries to contain a PrivacyManifest file:

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by MarcinSwierczek** [comment]
SDK version `2.1.1` containing [PrivacyInfo.xcprivacy](https://github.com/comapi/comapi-sdk-ios-objc/blob/master/PrivacyInfo.xcprivacy) has been released.
