### ISSUE TITLE
CMPAuthenticationManager not found

### ISSUE THREAD

**Issue by aleksandrach** [comapi/comapi-sdk-ios-objc#5]
CMPAuthenticationManager file is not existing.

**Comment by dkowalsky92** [comment]
Hey @aleksandrach,

**CMPAuthenticationManager** is a file in the SampleApp. If you downloaded/cloned the entire repo, you need to install the pods as they are not included in the repo. Run _pod install_ while in project's directory and open the generated **.xcworkspace** instead of **.xcodeproj** file.

Cheers,
Dominik

**Comment by aleksandrach** [comment]
Hi @dkowalsky92,

I installed the SDK using CocoaPods: Added pod 'CMPComapiFoundation' to the Podfile and then run pod install. Working in the .xcworkspace but the file is not there.

**Comment by dkowalsky92** [comment]
This file should not be present in the Pods, nor should it be imported by any SDK files. Are you sure you're not importing it in any of your files? 
If not, could you try running these three commands while in the project's directory and check again if the issue persists:

**sudo rm -fr ~/.cocoapods/repos/master
pod setup
pod install**

This helped my colleague as he had an issue installing the SDK, might help in your case. Reference:
https://stackoverflow.com/questions/25913733/unable-to-find-a-specification-in-cocoapods

**Comment by aleksandrach** [comment]
Thanks @dkowalsky92, but it still not working.

In the documentation it says: "_In order for the client to be able to start a session, the config's authenticationDelegate object must conform to the protocol's method:_" and the attached code is added. But there is no file CMPAuthenticationManager in the Pods.

![screen shot 2018-12-03 at 13 56 05](https://user-images.githubusercontent.com/8416920/49375005-57838600-f703-11e8-867d-db3d898a9238.png)
.

**Comment by dkowalsky92** [comment]
Yes, the CMPAuthenticationManager is not part of the SDK. It is just a helper class that generates a sample JWT token which should be generated by your backend server instead. The code you provided is part of the SampleApp, together with the CMPAuthenticationManager class. I agree this might be a bit confusing, I'll consider rewriting this part. What you need to do is, preferably, have your backend developers create a service that generates a JWT token from the given parameters of _generateTokenForNonce_ method OR you could recreate the class yourself. Here's the implementation of CMPAuthenticationManager:

<img width="868" alt="screenshot 2018-12-03 at 14 14 32" src="https://user-images.githubusercontent.com/22548305/49375876-ceba1980-f705-11e8-91fc-32a5cf9aa1be.png">

It's using **JWT**  installed via Cocoapods, reference: https://github.com/yourkarma/JWT.
