### ISSUE TITLE
Add property updatedOn to class CMPConversation

### ISSUE THREAD

**Issue by erolando** [comapi/comapi-sdk-ios-objc#8]
Please add property updatedOn to class CMPConversation

example:

if (JSON[@"_updatedOn"] && [JSON[@"_updatedOn"] isKindOfClass:NSString.class]) {
            self.updatedOn = [(NSString *)JSON[@"updatedOn"] asDate];
        }

thanks

**Comment by dkowalsky92** [comment]
If your intent is to retrieve the date of last sent message for specific conversation you can call the following method:

`[client.services.messaging getMessagesWithConversationID:self.conversation.id limit:1 from:0 completion:^(CMPResult<CMPGetMessagesResult *> *result) {
        if (!result.error && result.object && result.object.messages && result.object.messages.count > 0) {
            NSDate *date = result.object.messages[0].context.sentOn;
            // work on the date object;
        }
    }];`

The _updatedOn_ property is an internal information about conversation object itself.

Regards,
Dominik

**Comment by dkowalsky92** [comment]
Hey @erolando,

I discussed the case with the other developers and we decided to add the property to the class.

We'll add it in the next release.

Regards,
Dominik
